# fly.toml app configuration file generated for indoco-bot on 2026-04-20T15:28:01+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spa-single-agent-m'
primary_region = 'iad'

[build]

[env]
  PORT = '7860'

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[checks]
  [checks.health]
    port = 7860
    type = 'http'
    interval = '15s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpus = 2
  memory_mb = 1024
